### ISSUE TITLE
fix: project doesn't build due to kotlin gradle plugin incompatibility 

### ISSUE THREAD

**Issue by githubmonkey** [VeryGoodOpenSource/very_good_wear_app#30]
**Description**
Project doesn't build

**Steps To Reproduce**

1. Check out plain project
2. Resolve dependencies, try to run
3. Observe build error

```
Launching lib/main_development.dart on sdk gwear arm64 in debug mode...
Running Gradle task 'assembleDevelopmentDebug'...

FAILURE: Build failed with an exception.

* What went wrong:
The Android Gradle plugin supports only Kotlin Gradle plugin version 1.5.20 and higher.
The following dependencies do not satisfy the required version:
project ':wear' -> org.jetbrains.kotlin:kotlin-gradle-plugin:1.5.10

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org
```

**Expected Behavior**

**Screenshots**

**Additional Context**
There has been an issue filed with wear but it doesn't seem to get any traction. 
https://github.com/fluttercommunity/flutter_wear_plugin/issues/25

**Comment by ashishpatel1992** [comment]
Following +1

**Comment by renancaraujo** [comment]
That plugin has not been up-to-date in a while. I moved to a different Android API on #32 and internalized the native implementation.

**Comment by MayankDigital1** [comment]
> **Description** Project doesn't build
> 
> **Steps To Reproduce**
> 
> 1. Check out plain project
> 2. Resolve dependencies, try to run
> 3. Observe build error
> 
> ```
> Launching lib/main_development.dart on sdk gwear arm64 in debug mode...
> Running Gradle task 'assembleDevelopmentDebug'...
> 
> FAILURE: Build failed with an exception.
> 
> * What went wrong:
> The Android Gradle plugin supports only Kotlin Gradle plugin version 1.5.20 and higher.
> The following dependencies do not satisfy the required version:
> project ':wear' -> org.jetbrains.kotlin:kotlin-gradle-plugin:1.5.10
> 
> * Try:
> > Run with --stacktrace option to get the stack trace.
> > Run with --info or --debug option to get more log output.
> > Run with --scan to get full insights.
> 
> * Get more help at https://help.gradle.org
> ```
> 
> **Expected Behavior** A clear and concise description of what you expected to happen.
> 
> **Screenshots** If applicable, add screenshots to help explain your problem.
> 
> **Additional Context** There has been an issue filed with wear but it doesn't seem to get any traction. [fluttercommunity/flutter_wear_plugin#25](https://github.com/fluttercommunity/flutter_wear_plugin/issues/25)

**Comment by MayankDigital1** [comment]
Solution link : https://medium.com/@zalamayank2005/error-the-android-gradle-plugin-supports-only-kotlin-gradle-plugin-version-1-5-20-45c59d9b9f35
